# Generated by Django 5.2.4 on 2025-08-08 15:44

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва резюме')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публічне')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва шаблону')),
                ('description', models.TextField(verbose_name='Опис шаблону')),
                ('thumbnail', models.ImageField(upload_to='template_thumbnails/', verbose_name='Мініатюра')),
                ('html_file', models.FileField(upload_to='templates/', verbose_name='HTML файл шаблону')),
                ('css_file', models.FileField(blank=True, null=True, upload_to='templates/css/', verbose_name='CSS файл шаблону')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Ціна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Шаблон резюме',
                'verbose_name_plural': 'Шаблони резюме',
            },
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='По батькові')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Адреса')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='resume_photos/', verbose_name='Фото')),
                ('summary', models.TextField(blank=True, verbose_name='Про себе')),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to='builder.resume', verbose_name='Резюме')),
            ],
            options={
                'verbose_name': 'Особиста інформація',
                'verbose_name_plural': 'Особиста інформація',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Мова')),
                ('level', models.CharField(choices=[('a1', 'A1 - Початковий'), ('a2', 'A2 - Елементарний'), ('b1', 'B1 - Середній'), ('b2', 'B2 - Вище середнього'), ('c1', 'C1 - Просунутий'), ('c2', 'C2 - Вільний'), ('native', 'Рідна')], max_length=10, verbose_name='Рівень')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='builder.resume', verbose_name='Резюме')),
            ],
            options={
                'verbose_name': 'Мова',
                'verbose_name_plural': 'Мови',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200, verbose_name='Навчальний заклад')),
                ('degree', models.CharField(max_length=100, verbose_name='Ступінь')),
                ('field_of_study', models.CharField(max_length=100, verbose_name='Спеціальність')),
                ('start_date', models.DateField(verbose_name='Дата початку')),
                ('end_time', models.DateField(blank=True, null=True, verbose_name='Дата завершення')),
                ('currently_studying', models.BooleanField(default=False, verbose_name='Навчаюсь зараз')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='builder.resume', verbose_name='Резюме')),
            ],
            options={
                'verbose_name': 'Освіта',
                'verbose_name_plural': 'Освіта',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва сертифікату')),
                ('issuing_organization', models.CharField(max_length=200, verbose_name='Організація')),
                ('issue_date', models.DateField(verbose_name='Дата отримання')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Термін дії')),
                ('credential_id', models.CharField(blank=True, max_length=100, verbose_name='ID сертифікату')),
                ('credential_url', models.URLField(blank=True, verbose_name='Посилання')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='builder.resume', verbose_name='Резюме')),
            ],
            options={
                'verbose_name': 'Сертифікат',
                'verbose_name_plural': 'Сертифікати',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='ResumeExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('html', 'HTML')], max_length=10, verbose_name='Формат')),
                ('file', models.FileField(upload_to='resume_exports/', verbose_name='Файл')),
                ('exported_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата експорту')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='builder.resume', verbose_name='Резюме')),
            ],
            options={
                'verbose_name': 'Експорт резюме',
                'verbose_name_plural': 'Експорти резюме',
                'ordering': ['-exported_at'],
            },
        ),
        migrations.AddField(
            model_name='resume',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='builder.resumetemplate', verbose_name='Шаблон'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва навички')),
                ('level', models.CharField(choices=[('beginner', 'Початківець'), ('intermediate', 'Середній'), ('advanced', 'Просунутий'), ('expert', 'Експерт')], default='intermediate', max_length=20, verbose_name='Рівень')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='Категорія')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='builder.resume', verbose_name='Резюме')),
            ],
            options={
                'verbose_name': 'Навичка',
                'verbose_name_plural': 'Навички',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='builder_user_groups', related_query_name='builder_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='builder_user_permissions', related_query_name='builder_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Користувач',
                'verbose_name_plural': 'Користувачі',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='builder.user', verbose_name='Користувач'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Зміст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.user', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Оголошення',
                'verbose_name_plural': 'Оголошення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, verbose_name='Компанія')),
                ('position', models.CharField(max_length=100, verbose_name='Посада')),
                ('start_date', models.DateField(verbose_name='Дата початку')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата завершення')),
                ('currently_working', models.BooleanField(default=False, verbose_name='Працюю зараз')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='builder.resume', verbose_name='Резюме')),
            ],
            options={
                'verbose_name': 'Досвід роботи',
                'verbose_name_plural': 'Досвід роботи',
                'ordering': ['-start_date'],
            },
        ),
    ]
