# Generated by Django 5.2.4 on 2025-08-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_alter_resumetemplate_css_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumetemplate',
            name='css_file',
            field=models.FileField(blank=True, null=True, upload_to='template_previews/templates/css/', verbose_name='CSS файл шаблону'),
        ),
        migrations.AlterField(
            model_name='resumetemplate',
            name='html_file',
            field=models.FileField(upload_to='template_previews/templates/', verbose_name='HTML файл шаблону'),
        ),
        migrations.AlterField(
            model_name='resumetemplate',
            name='thumbnail',
            field=models.ImageField(upload_to='template_previews/template_thumbnails/', verbose_name='Мініатюра'),
        ),
    ]
