# Generated by Django 5.2.4 on 2025-08-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_alter_resumetemplate_css_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumetemplate',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Преміум шаблон'),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='preview_image',
            field=models.ImageField(default=11, upload_to='template_previews/', verbose_name="Зображення прев'ю"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resumetemplate',
            name='css_file',
            field=models.FileField(blank=True, null=True, upload_to='templates/css/', verbose_name='CSS файл шаблону'),
        ),
        migrations.AlterField(
            model_name='resumetemplate',
            name='html_file',
            field=models.FileField(upload_to='templates/', verbose_name='HTML файл шаблону'),
        ),
        migrations.AlterField(
            model_name='resumetemplate',
            name='thumbnail',
            field=models.ImageField(upload_to='template_thumbnails/', verbose_name='Мініатюра'),
        ),
    ]
