# Generated by Django 5.2.4 on 2025-08-22 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_resumetemplate_is_premium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_instances', to='builder.resumetemplate', verbose_name='Шаблон'),
        ),
    ]
