# Generated by Django 5.2.4 on 2025-08-22 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_alter_resume_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='builder.resumetemplate', verbose_name='Шаблон'),
        ),
    ]
