# Generated by Django 5.2.6 on 2025-09-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0006_alter_resume_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='share_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
